### ISSUE TITLE
Update old test cases to reflect changes to the parser

### ISSUE THREAD

**Issue by lazorchakp** [baileyparker/phf-compilers-tests#14]
Many of the *.cst test cases need to be remade, since their corresponding *.sim files are no longer parsed properly after implementing the new context conditions. I personally do not have time to resolve this issue until after Assignment 3 is due. In the meantime, know that multiple tests will fail even if you have working code!

**Comment by baileyparker** [comment]
Indeed. Just made piazza post about this. I think the long term solution is that we can run the CST fixtures that expect errors (they should still error for some reason). But we need to add a flag to disable the ones that are expected to succeed (because they may not be syntactically valid). It would be nice to port some of them to `fixtures/symbol_table/`.

**Comment by baileyparker** [comment]
The official solution is now to `run_harness --skip-cst-passes`. This will skip CST test cases that could fail due to having semantic errors (but being syntactically valid and should be able to past just the CST without the semantic analysis added).
